import { MantineThemeOverride } from '@mantine/core'

export const theme: MantineThemeOverride = {
  fontFamily: 'var(--font-primary)',
  radius: {
    md: 'var(--radius)',
  },
  defaultRadius: 'md',
  colors: {
    'primary': [
      'var(--color-primary-0)',
      'var(--color-primary-1)',
      'var(--color-primary-2)',
      'var(--color-primary-3)',
      'var(--color-primary-4)',
      'var(--color-primary-5)',
      'var(--color-primary-6)',
      'var(--color-primary-7)',
      'var(--color-primary-8)',
      'var(--color-primary-9)',
    ],
    'accent': [
      'var(--color-accent-0)',
      'var(--color-accent-1)',
      'var(--color-accent-2)',
      'var(--color-accent-3)',
      'var(--color-accent-4)',
      'var(--color-accent-5)',
      'var(--color-accent-6)',
      'var(--color-accent-7)',
      'var(--color-accent-8)',
      'var(--color-accent-9)',
    ],
    'background': [
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
      'var(--color-background)',
    ],
    'background-alt': [
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
      'var(--color-background-alt)',
    ],
  },
  primaryColor: 'primary',
  black: 'var(--color-text)',
}
